// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAibFXFz9v7CyNT48GMRZAx-hiPBk3Hw_Y',
    appId: '1:728415413382:web:97f9c7643812f5918d9d07',
    messagingSenderId: '728415413382',
    projectId: 'csc464-p006',
    authDomain: 'csc464-p006.firebaseapp.com',
    storageBucket: 'csc464-p006.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_sDistY5MLVVSxaG42IjTdW0U_tLvVLY',
    appId: '1:728415413382:android:edb56e0e151e95808d9d07',
    messagingSenderId: '728415413382',
    projectId: 'csc464-p006',
    storageBucket: 'csc464-p006.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVgR-NoMOokxVseCNHG1nusnhrxjL8eVk',
    appId: '1:728415413382:ios:c7f557d93ced455a8d9d07',
    messagingSenderId: '728415413382',
    projectId: 'csc464-p006',
    storageBucket: 'csc464-p006.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVgR-NoMOokxVseCNHG1nusnhrxjL8eVk',
    appId: '1:728415413382:ios:c7f557d93ced455a8d9d07',
    messagingSenderId: '728415413382',
    projectId: 'csc464-p006',
    storageBucket: 'csc464-p006.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAibFXFz9v7CyNT48GMRZAx-hiPBk3Hw_Y',
    appId: '1:728415413382:web:0ae5b332c80b8a468d9d07',
    messagingSenderId: '728415413382',
    projectId: 'csc464-p006',
    authDomain: 'csc464-p006.firebaseapp.com',
    storageBucket: 'csc464-p006.firebasestorage.app',
  );

}